# Site settings
title: SoftAndoWetto's Blog Page
email: your-email@example.com
description: "Write an awesome description for your site here."
url: "https://softandowetto.github.io" # Replace with your GitHub Pages URL
baseurl: "" # leave empty unless using a subfolder

twitter_username: jekyllrb
github_username: jekyll

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true

sass:
  sass_dir: assets/css
  style: compressed

# Collections
collections:
  blog:
    output: true
    permalink: /blog/:title
  writeups:
    output: true
    permalink: /writeup/:title
  resources:
    output: true
    permalink: /resources/:title

defaults:
  -
    scope:
      path: ""
      type: "blog"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "writeups"
    values:
      layout: "post"

# Optional: exclude unnecessary files from build
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

